### ISSUE TITLE
split_TADs error: IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by jrhawley** [GuangyWang/TADsplimer#2]
Hi @GuangyWang, thanks for this work and making this tool.
I've tried to use TADsplimer to compare two samples, but I end up running into this issue for some data I've been working with.
I've been able to run the example simulation data from this repository without issue, but I often run into this problem with my own data, and I'm not sure how to fix this.

```shell
> docker run -v /path/to/data/:/data/ -t guangywang/tadsplimer:v1.0.2 python3 /bin/TADsplimer.py split_TADs -c /data/example1.wide.mtx,/data/example2.wide.mtx --contact_maps_aliases example1,example2 -o /data/Comparison/example1-example2
/data/example1.wide.mtx
auto: 13.3682828283 1.47051111111
example1.-500.500.subchr
example1.0.150.subchr
/bin/TAD_calling.py:402: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
  unique_tad = sorted_tad[row_mask]
Traceback (most recent call last):
  File "/bin/TADsplimer.py", line 371, in <module>
    split_TADs(command='split_TADs')
  File "/bin/TADsplimer.py", line 250, in split_TADs
    TAD_calling.subTAD_calling(tmp_dir1, up1, down1, aliase=aliases[0])
  File "/bin/TAD_calling.py", line 402, in subTAD_calling
    unique_tad = sorted_tad[row_mask]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

It looks like there's an issue when creating the `row_mask` vector in `subTAD_calling`, [here](https://github.com/GuangyWang/TADsplimer/blob/master/src/TAD_calling.py#L401).

This error doesn't always happen (e.g. your simulation data in `example/` works without issue), but for most other data I've tried, the error is thrown.

The example data I've used here can be found in [this Gist](https://gist.github.com/jrhawley/62665f8666b453977b8668b14621fbe4). Thanks

**Comment by GuangyWang** [comment]
Hi 

The input file need to be square matrix. I tested your input file. Their size is 149*150. Could you make it to a square matrix and try again? If you have any other issues, please let me know.

**Comment by GuangyWang** [comment]
> Hi @GuangyWang, thanks for this work and making this tool.
> I've tried to use TADsplimer to compare two samples, but I end up running into this issue for some data I've been working with.
> I've been able to run the example simulation data from this repository without issue, but I often run into this problem with my own data, and I'm not sure how to fix this.
> 
> ```shell
> > docker run -v /path/to/data/:/data/ -t guangywang/tadsplimer:v1.0.2 python3 /bin/TADsplimer.py split_TADs -c /data/example1.wide.mtx,/data/example2.wide.mtx --contact_maps_aliases example1,example2 -o /data/Comparison/example1-example2
> /data/example1.wide.mtx
> auto: 13.3682828283 1.47051111111
> example1.-500.500.subchr
> example1.0.150.subchr
> /bin/TAD_calling.py:402: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
>   unique_tad = sorted_tad[row_mask]
> Traceback (most recent call last):
>   File "/bin/TADsplimer.py", line 371, in <module>
>     split_TADs(command='split_TADs')
>   File "/bin/TADsplimer.py", line 250, in split_TADs
>     TAD_calling.subTAD_calling(tmp_dir1, up1, down1, aliase=aliases[0])
>   File "/bin/TAD_calling.py", line 402, in subTAD_calling
>     unique_tad = sorted_tad[row_mask]
> IndexError: index 0 is out of bounds for axis 0 with size 0
> ```
> 
> It looks like there's an issue when creating the `row_mask` vector in `subTAD_calling`, [here](https://github.com/GuangyWang/TADsplimer/blob/master/src/TAD_calling.py#L401).
> 
> This error doesn't always happen (e.g. your simulation data in `example/` works without issue), but for most other data I've tried, the error is thrown.
> 
> The example data I've used here can be found in [this Gist](https://gist.github.com/jrhawley/62665f8666b453977b8668b14621fbe4). Thanks

Hi

The input file need to be square matrix. I tested your input file. Their size is 149*150. Could you make it to a square matrix and try again? If you have any other issues, please let me know.

**Comment by jrhawley** [comment]
Thanks for taking a look at this.
When I load the data from the previous gist into R with `data.table`, I get

```R
> library("data.table")
> example1 <- fread("example1.wide.txt")
> example2 <- fread("example2.wide.txt")
> dim(example1)
150 150
> dim(example2)
150 150
```

Is there an issue with newlines/carriage returns/accidentally reading the first line as a header that is causing this problem?
Because it looks like both the matrices I posted are 150 x 150 elements

**Comment by GuangyWang** [comment]
> Thanks for taking a look at this.
> When I load the data from the previous gist into R with `data.table`, I get
> 
> ```r
> > library("data.table")
> > example1 <- fread("example1.wide.txt")
> > example2 <- fread("example2.wide.txt")
> > dim(example1)
> 150 150
> > dim(example2)
> 150 150
> ```
> 
> Is there an issue with newlines/carriage returns/accidentally reading the first line as a header that is causing this problem?
> Because it looks like both the matrices I posted are 150 x 150 elements

Hi jrhawley,

I have updated TADsplimer to version 1.0.3. That bug was fixed. You can download and test the new version following Readme.

If you have any questions, please let me know. In case I miss your questions, you can also send me email. My email address is guangywang@gmail.com.

**Comment by Yulong663** [comment]
> This appears to be working in the v1.0.3 docker image now. Thanks for looking into this, much appreciated!

Hi jrhawley ,recently i'm dealing with some hic dataset and trying to implement the TADsplimer too. I want to konw that the input of "split_TADs" is dense matrix format of traditional format (i.e pos1 pos2 value ) dumped from .hic file. Thanks in advance :)

**Comment by jrhawley** [comment]
> Hi jrhawley ,recently i'm dealing with some hic dataset and trying to implement the TADsplimer too. I want to konw that the input of "split_TADs" is dense matrix format of traditional format (i.e pos1 pos2 value ) dumped from .hic file. Thanks in advance :)

Hi @Yulong663, I had to use dense, wide matrices here. I dumped them from the [Cooler](https://cooler.readthedocs.io) files I had my Hi-C data stored in, so I assume you'll have to do something similar from your `.hic` files before running TADsplimer
